<?php

$title = $this->translate('Users list');
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('authentication_admin_user', array('action' => 'add')); ?>"><?php echo $this->translate('Add new user'); ?></a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate('Username'); ?></th>
    <th><?php echo $this->translate('Email'); ?></th>
    <th><?php echo $this->translate('Is super user'); ?></th>
    <th>&nbsp;</th>
</tr>


<?php if (!count($users)) : ?>
<tr><td colspan="4"><?php echo $this->translate('No users found'); ?></td></tr>
<?php endif; ?>

<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->username); ?></td>
    <td><?php echo $this->escapeHtml($user->email); ?></td>
    <td><?php echo $user->is_super_user ? $this->translate('Yes') : $this->translate('No'); ?></td>
    <td>
        <a href="<?php echo $this->url('authentication_admin_user', array('action' => 'edit', 'id' => $user->id)); ?>"><?php echo $this->translate('Edit'); ?></a>
        <a href="<?php echo $this->url('authentication_admin_user', array('action' => 'delete', 'id' => $user->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
